import { TemplateConfigModel } from "./models/TemplateConfig";

const defaultSections = [
  { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "default" as const } },
  { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "light" as const, spacing: "default" as const } },
  { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "light" as const, spacing: "default" as const } },
  { type: "schedule" as const, enabled: true, layout: "timeline", style: { bgStyle: "light" as const, spacing: "default" as const } },
  { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "light" as const, spacing: "default" as const } },
  { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "light" as const, spacing: "default" as const } },
  { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "primary" as const, spacing: "default" as const } },
];

export const builtInTemplates = [
  {
    name: "Modern",
    slug: "modern",
    description: "Clean, professional design with MongoDB green gradient hero and elegant card layouts",
    baseTemplate: "modern",
    isBuiltIn: true,
    isDefault: true,
    colors: {
      primary: "#00684A",
      secondary: "#13AA52",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#212121",
      textSecondary: "#666666",
      heroBg: "#00684A",
      heroBgEnd: "#004D37",
      heroText: "#FFFFFF",
      buttonBg: "#FFFFFF",
      buttonText: "#00684A",
    },
    typography: {
      headingFont: "system" as const,
      bodyFont: "system" as const,
      headingWeight: 700 as const,
      scale: "default" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "default" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "schedule" as const, enabled: true, layout: "timeline", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "primary" as const, spacing: "default" as const } },
    ],
    cards: {
      borderRadius: 8 as const,
      style: "shadow" as const,
      accentPosition: "none" as const,
    },
    hero: {
      style: "gradient" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.85,
      buttonStyle: "rounded" as const,
    },
  },
  {
    name: "Bold",
    slug: "bold",
    description: "Vibrant blue-to-purple gradient with oversized typography and dramatic card animations",
    baseTemplate: "bold",
    isBuiltIn: true,
    isDefault: false,
    colors: {
      primary: "#0068F9",
      secondary: "#B039F8",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#212121",
      textSecondary: "#666666",
      heroBg: "#0068F9",
      heroBgEnd: "#B039F8",
      heroText: "#FFFFFF",
      buttonBg: "#FFFFFF",
      buttonText: "#0068F9",
    },
    typography: {
      headingFont: "system" as const,
      bodyFont: "system" as const,
      headingWeight: 900 as const,
      scale: "large" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "primary" as const, spacing: "spacious" as const } },
      { type: "schedule" as const, enabled: true, layout: "timeline", style: { bgStyle: "light" as const, spacing: "spacious" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "light" as const, spacing: "spacious" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "light" as const, spacing: "spacious" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
    ],
    cards: {
      borderRadius: 16 as const,
      style: "shadow" as const,
      accentPosition: "none" as const,
    },
    hero: {
      style: "gradient" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.9,
      buttonStyle: "pill" as const,
    },
  },
  {
    name: "Tech",
    slug: "tech",
    description: "Dark terminal-inspired design with neon green accents and monospace typography",
    baseTemplate: "tech",
    isBuiltIn: true,
    isDefault: false,
    colors: {
      primary: "#00ED64",
      secondary: "#00ED64",
      background: "#0a0e27",
      surface: "rgba(0, 237, 100, 0.08)",
      text: "#00ED64",
      textSecondary: "#B0FFB0",
      heroBg: "#0a0e27",
      heroBgEnd: "#1a1f3a",
      heroText: "#00ED64",
      buttonBg: "#00ED64",
      buttonText: "#0a0e27",
    },
    typography: {
      headingFont: "mono" as const,
      bodyFont: "mono" as const,
      headingWeight: 700 as const,
      scale: "default" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "dark" as const, spacing: "spacious" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "schedule" as const, enabled: true, layout: "list", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "dark" as const, spacing: "default" as const } },
    ],
    cards: {
      borderRadius: 8 as const,
      style: "border" as const,
      accentPosition: "none" as const,
    },
    hero: {
      style: "gradient" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.9,
      buttonStyle: "rounded" as const,
    },
  },
  {
    name: "Leafy",
    slug: "leafy",
    description: "Clean white MongoDB LeafyGreen-inspired design with green accent bars and border-based cards",
    baseTemplate: "leafy",
    isBuiltIn: true,
    isDefault: false,
    colors: {
      primary: "#00684A",
      secondary: "#13AA52",
      background: "#FFFFFF",
      surface: "#F9FBFA",
      text: "#001E2B",
      textSecondary: "#3D4F58",
      heroBg: "#FFFFFF",
      heroBgEnd: "#FFFFFF",
      heroText: "#001E2B",
      buttonBg: "#00684A",
      buttonText: "#FFFFFF",
    },
    typography: {
      headingFont: "system" as const,
      bodyFont: "system" as const,
      headingWeight: 700 as const,
      scale: "default" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "schedule" as const, enabled: true, layout: "timeline", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "primary" as const, spacing: "default" as const } },
    ],
    cards: {
      borderRadius: 12 as const,
      style: "border" as const,
      accentPosition: "top" as const,
    },
    hero: {
      style: "light" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.92,
      buttonStyle: "rounded" as const,
    },
  },
  {
    name: "Atlas",
    slug: "atlas",
    description: "Dark glassmorphism design with dot-grid mesh, connected-node timeline, and green-blue-purple accents",
    baseTemplate: "atlas",
    isBuiltIn: true,
    isDefault: false,
    colors: {
      primary: "#13AA52",
      secondary: "#0068F9",
      background: "#001E2B",
      surface: "rgba(17, 39, 51, 0.6)",
      text: "#FFFFFF",
      textSecondary: "#B8C4C2",
      heroBg: "#001E2B",
      heroBgEnd: "#112733",
      heroText: "#FFFFFF",
      buttonBg: "#13AA52",
      buttonText: "#001E2B",
    },
    typography: {
      headingFont: "system" as const,
      bodyFont: "system" as const,
      headingWeight: 800 as const,
      scale: "large" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "dark" as const, spacing: "spacious" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "schedule" as const, enabled: true, layout: "timeline", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "dark" as const, spacing: "default" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
    ],
    cards: {
      borderRadius: 12 as const,
      style: "glass" as const,
      accentPosition: "top" as const,
    },
    hero: {
      style: "gradient" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.9,
      buttonStyle: "rounded" as const,
    },
  },
  {
    name: "Community",
    slug: "community",
    description: "Colorful community-focused design with rotating green-blue-purple accents and numbered stepper schedule",
    baseTemplate: "community",
    isBuiltIn: true,
    isDefault: false,
    colors: {
      primary: "#13AA52",
      secondary: "#0068F9",
      background: "#FFFFFF",
      surface: "#F9FBFA",
      text: "#001E2B",
      textSecondary: "#5C6C75",
      heroBg: "#00684A",
      heroBgEnd: "#0068F9",
      heroText: "#FFFFFF",
      buttonBg: "#FFFFFF",
      buttonText: "#00684A",
    },
    typography: {
      headingFont: "system" as const,
      bodyFont: "system" as const,
      headingWeight: 800 as const,
      scale: "large" as const,
    },
    sections: [
      { type: "hero" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
      { type: "about" as const, enabled: true, layout: "default", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "prizes" as const, enabled: true, layout: "grid-3", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "schedule" as const, enabled: true, layout: "stepper", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "partners" as const, enabled: true, layout: "tiered", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "faq" as const, enabled: true, layout: "accordion", style: { bgStyle: "light" as const, spacing: "default" as const } },
      { type: "cta" as const, enabled: true, layout: "default", style: { bgStyle: "gradient" as const, spacing: "spacious" as const } },
    ],
    cards: {
      borderRadius: 16 as const,
      style: "border" as const,
      accentPosition: "top" as const,
    },
    hero: {
      style: "gradient" as const,
      gradientDirection: "135deg",
      overlayOpacity: 0.85,
      buttonStyle: "pill" as const,
    },
  },
];

/**
 * Seed built-in template configs. Idempotent — only inserts missing templates by slug.
 */
export async function seedBuiltInTemplates() {
  let inserted = 0;

  for (const template of builtInTemplates) {
    const existing = await TemplateConfigModel.findOne({ slug: template.slug });
    if (!existing) {
      await TemplateConfigModel.create(template);
      inserted++;
    }
  }

  return inserted;
}
